# Generated by Django 5.0.6 on 2024-07-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ine_files', models.FileField(default='default_files/placeholder.pdf', upload_to='')),
                ('Curp_files', models.FileField(default='default_files/placeholder.pdf', upload_to='')),
                ('Acta_files', models.FileField(default='default_files/placeholder.pdf', upload_to='')),
                ('Comp_files', models.FileField(default='default_files/placeholder.pdf', upload_to='')),
            ],
        ),
    ]
