# Generated by Django 5.0.6 on 2024-07-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='files',
        ),
        migrations.AddField(
            model_name='firm',
            name='Ine_files',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
