# Generated by Django 5.0.6 on 2024-07-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='Acta_files',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='firm',
            name='Comp_files',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='firm',
            name='Curp_files',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='firm',
            name='Ine_files',
            field=models.FileField(upload_to=''),
        ),
    ]
