# Generated by Django 5.0.6 on 2024-07-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_firm_acta_files_alter_firm_comp_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='Acta_files',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='Comp_files',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='Curp_files',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='Ine_files',
            field=models.FileField(upload_to='files/'),
        ),
    ]
