# Generated by Django 5.0.6 on 2024-07-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_firm_firma_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='Firma_files',
        ),
    ]
